# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2018-03-30 06:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Annotations',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('videoName', models.TextField()),
                ('t', models.TextField()),
                ('img', models.TextField()),
                ('num', models.IntegerField()),
                ('obj', models.TextField()),
                ('xmin', models.IntegerField()),
                ('xmax', models.IntegerField()),
                ('ymin', models.IntegerField()),
                ('ymax', models.IntegerField()),
            ],
        ),
    ]
