# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2018-04-02 13:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipescape', '0002_idnamepair'),
    ]

    operations = [
        migrations.CreateModel(
            name='Equations',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('videoName', models.TextField()),
                ('t', models.TextField()),
                ('step_num', models.IntegerField()),
                ('step_des', models.TextField()),
                ('step_start', models.IntegerField()),
                ('step_end', models.IntegerField()),
            ],
        ),
    ]
